### ISSUE TITLE
Accordian

### ISSUE THREAD

**Issue by PMLS3** [Julien-R44/unocss-preset-flowbite#1]
Thank you for a great repo... I know you said not everything has been implemented. I just want to make sure, is all javascript components (accordian etc) not working?

**Comment by Julien-R44** [comment]
Hi, nope, should works. However, you need to includes the flowbite javascript plugin from their npm package. My plugin is just a replacement for the Flowbite Tailwind plugin. So it just handle the styling part. Not the interactivity/javascript part, like required for accordions.

https://flowbite.com/docs/getting-started/quickstart/#require-via-npm

**Comment by Julien-R44** [comment]
Closing since not actionable. Feel free to re-open the issue if you encounter any issue related to this package!
